import Navigation from "./_components/navigation";

export const metadata = {
  title: "THE WILD OASIS",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <Navigation />
        {children}
      </body>
    </html>
  );
}
