import Logo from "@/app/_components/Logo";
import Navigation from "./_components/navigation";
import "@/app/_styles/globals.css";
import { Josefin_Sans } from "next/font/google";
import Header from "./_components/Header";

export const metadata = {
  title: "THE WILD OASIS",
  description: "Generated by create next app",
};

const Josefin = Josefin_Sans({
  subsets: ['latin'],
  display: 'swap',
})

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${Josefin.className} relative antialiased bg-primary-950 text-primary-100 min-h-screen flex flex-col`}>
        <Header></Header>
        <div className="flex-1 px-8 py-12">
          <main className="max-w-7xl mx-auto">{children}</main>
        </div>
      </body>
    </html>
  );
}
